# Generated by Django 4.2.6 on 2023-11-09 14:40

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Зображення')),
                ('country', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Зображення')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок посту')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Зміст посту')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикації')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_photos/', verbose_name='Фотографія')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
                ('article', models.PositiveIntegerField(unique=True, verbose_name='Артикул')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
                ('article', models.PositiveIntegerField(unique=True, verbose_name='Артикул')),
            ],
            options={
                'verbose_name': 'Програмне забезпечення',
                'verbose_name_plural': 'Програмне забезпечення',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Зображення')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Сервісна підтримка',
                'verbose_name_plural': 'Сервісна підтримка',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Зображення')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Готове рішення',
                'verbose_name_plural': 'Готові рішення',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Зображення')),
                ('slug', autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Технічна підтримка',
                'verbose_name_plural': 'Технічна підтримка',
            },
        ),
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
