# Generated by Django 4.2.6 on 2023-11-13 13:18

import autoslug.fields
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Назва проекту"),
                ),
                ("client", models.TextField(blank=True, verbose_name="Замовник")),
                ("adress", models.TextField(blank=True, verbose_name="Адреса")),
                ("realization_date", models.DateField(verbose_name="Дата реалізації")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Опис"),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Зображення"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default="", editable=False, populate_from="name", unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Виконаний проект",
                "verbose_name_plural": "Виконані проекти",
            },
        ),
    ]
