# Generated by Django 4.2.6 on 2023-11-14 11:45

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Назва")),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Опис"),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Зображення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пропозиція",
                "verbose_name_plural": "Пропозиції",
            },
        ),
    ]
