# Generated by Django 4.2.6 on 2023-11-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="type",
            field=models.CharField(
                choices=[("hardware", "Железо"), ("software", "Софт")],
                default="hardware",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
