# Generated by Django 4.2.6 on 2023-11-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_offer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
        migrations.AlterField(
            model_name="offer",
            name="type",
            field=models.CharField(
                choices=[
                    ("hardware", "Железо"),
                    ("software", "Софт"),
                    ("service", "Сервіс"),
                    ("support", "Підтримка"),
                ],
                default="hardware",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
