# Generated by Django 4.2.6 on 2023-11-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackMessage',
        ),
    ]
