# Generated by Django 4.2.6 on 2023-11-13 09:31

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0003_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Міссія компанії"
                    ),
                ),
            ],
            options={
                "verbose_name": "Міссія компанії",
                "verbose_name_plural": "Міссія компанії",
            },
        ),
    ]
