# Generated by Django 4.2.6 on 2023-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0004_mission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ім'я")),
                (
                    "second_name",
                    models.CharField(max_length=100, verbose_name="Фамілія"),
                ),
                ("department", models.TextField()),
                (
                    "phone_number",
                    models.TextField(blank=True, null=True, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.TextField(blank=True, null=True, verbose_name="E-mail"),
                ),
                (
                    "photo_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Фотографія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Співробітник компанії",
                "verbose_name_plural": "Співробітники компанії",
            },
        ),
    ]
