# Generated by Django 4.2.6 on 2023-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0005_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="email",
            field=models.TextField(null=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone_number",
            field=models.TextField(null=True, verbose_name="Телефон"),
        ),
    ]
